### ISSUE TITLE
dmeetup logo

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/dmeetup#51]
dmeetup logo proposals

upload your proposal in comments area

**Comment by murillojorge** [comment]
Aquí les dejo un par de ideas, para que las discutamos.

![dmeetup-logo-p01](https://user-images.githubusercontent.com/1179619/42481944-321d2b98-83a2-11e8-802e-4491945fc58d.png)

![dmeetup-logo-p02](https://user-images.githubusercontent.com/1179619/42481972-4ca6bf88-83a2-11e8-93d2-da699996ad42.png)

**Comment by gaboesquivel** [comment]
nice! me gusta el segundo 👍

**Comment by gaboesquivel** [comment]
nice! I like the second one 👍 

hmm I think should consult about trademark legal considerations

**Comment by xavier506** [comment]
nice!
a mi me gusta el primero
:smiley:
me gusta que sea mas sencillo
pero los dos están super bien! 🏆

**Comment by eduzambl** [comment]
i would like to know what are the elements representing.

**Comment by gadriv** [comment]
¿Cual es la tipografía que se esta utilizando?

**Comment by murillojorge** [comment]
The geometric elements are sections of the EOS symbol. I believe there's a sense of belonging that comes with the use of new technologies and it could help to bring identity to an extent. Like being part of a family. 
At this stage, and I believe for a while, early adopters will come from EOS, or blockchain related sources. At a later point rebranding to wider audiences could be a consideration.
 I'm personally leaning towards the first one since it's easier to read.

**Comment by edgar-eoscostarica** [comment]
I like the first one as well. Its simple, you can clearly read the "D" and also makes a nice node to the EOS logo.  Could we see a version that fuses both?  Use the "D" for the first logo but the the text from the second logo that has the "eetup" in lower case?

**Comment by murillojorge** [comment]
The font I'm using is Resamitz by Gluk. 
http://www.glukfonts.pl/font.php?font=Resamitz

It's Open Font Licenced.
https://opensource.org/licenses/OFL-1.1

**Comment by gaboesquivel** [comment]
I think we have a logo.  Version 1.  If you agree we can close this.
